# Human Tasks:
# 1. Ensure the ENV environment variable is set in your deployment pipeline
# 2. Verify that the namespace name follows DNS-1123 label format
# 3. Confirm that the labels and annotations comply with Kubernetes naming conventions

# Kubernetes v1.24+ namespace configuration
# Addresses requirements:
# - Environment Isolation (11.4 Orchestration/11.4.2 Kubernetes Resources)
# - Multi-Environment Support (11.1 Deployment Environment/11.1.1 Environment Architecture)

apiVersion: v1
kind: Namespace
metadata:
  name: code-generation-app
  labels:
    # Core application labels
    app: code-generation-app
    environment: ${ENV}
    managed-by: kustomize
    
    # Additional labels for resource organization
    tier: application
    version: v1
    
  annotations:
    # Application metadata
    app.kubernetes.io/part-of: code-generation-app
    app.kubernetes.io/managed-by: kustomize
    description: "Namespace for Code Generation Application components"
    
    # Resource management annotations
    scheduler.alpha.kubernetes.io/node-selector: "env=${ENV}"
    net.beta.kubernetes.io/network-policy: "enabled"
    
    # Security annotations
    security.kubernetes.io/enforce-pod-security: "restricted"
    
    # Monitoring annotations
    monitoring.kubernetes.io/enable: "true"
    prometheus.io/scrape: "true"
    
spec:
  # Namespace finalization for proper cleanup
  finalizers:
    - kubernetes