# Human Tasks:
# 1. Ensure all secret values are base64 encoded before storing in the secrets.env file
# 2. Verify that the database credentials match the Cloud SQL instance configuration
# 3. Confirm that the JWT secret key meets minimum length requirements (32 bytes recommended)
# 4. Validate that the Google Cloud service account has the required permissions
# 5. Ensure Redis password meets complexity requirements
# 6. Implement regular secret rotation procedures
# 7. Configure encryption-at-rest for the Kubernetes secrets

# Kubernetes v1.24+ Secret configuration
# Addresses requirements:
# - Data Security (10.2 Data Security/10.2.1 Data Classification)
# - Authentication Configuration (7.1 High-Level Architecture/Authentication Layer)
# - Database Security (10.2.3 Database Security)

apiVersion: v1
kind: Secret
metadata:
  name: code-generation-app-secrets
  namespace: code-generation-app
  labels:
    app: code-generation-app
    environment: ${ENV}
    managed-by: kustomize
    tier: security
    component: credentials
  annotations:
    # Security annotations
    vault.hashicorp.com/agent-inject: "true"
    encryption.kubernetes.io/encrypted: "true"
    
    # Rotation annotations
    secret.kubernetes.io/rotation-period: "30d"
    secret.kubernetes.io/next-rotation: "${NEXT_ROTATION_DATE}"
    
    # Description and purpose
    description: "Application secrets for the Code Generation service"
    purpose: "Store sensitive configuration and credentials"
    
    # Compliance annotations
    security.compliance/data-classification: "restricted"
    security.compliance/access-control: "rbac-only"
    
type: Opaque
data:
  # Database credentials
  # Required for: 10.2.3 Database Security
  DATABASE_USER: ${BASE64_DB_USER}
  DATABASE_PASSWORD: ${BASE64_DB_PASSWORD}
  
  # Authentication secrets
  # Required for: 7.1 High-Level Architecture/Authentication Layer
  JWT_SECRET_KEY: ${BASE64_JWT_SECRET}
  
  # Cloud service account credentials
  # Required for: 10.2 Data Security/10.2.1 Data Classification
  GOOGLE_CLOUD_CREDENTIALS: ${BASE64_GCP_CREDS}
  
  # Cache layer credentials
  # Required for: 10.2 Data Security/10.2.1 Data Classification
  REDIS_PASSWORD: ${BASE64_REDIS_PASSWORD}

# Immutability ensures secrets can't be modified after creation
immutable: true